#!/bin/sh

DF_DIR=$HOME/misc/games/dwarf_fortress_34_11

cd "${DF_DIR}"

# Work around for bug in Debian/Ubuntu SDL patch.
export SDL_DISABLE_LOCK_KEYS=1

# Centre the screen.  Messes up resizing.
# export SDL_VIDEO_CENTERED=1

# Go, go, go! :)
./libs/Dwarf_Fortress $*
