#! /usr/bin/env ruby

=begin

Convert audio files to sped-up mp3.
Shells out to ffmpeg(1).

Created: 18 Apr 2013
Author: Victor Deryagin <vderyagin@gmail.com>

=end

require 'optparse'
require 'pathname'

options = {
  speed: 2.0,
  dir: Pathname.new(Dir.pwd),
  keep_original: false,
  fat32: true,
}

parser = OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename($PROGRAM_NAME)} [options] FILE..."

  opts.on('-s SPEED', '--speed SPEED', Float,
          "Specify speedup factor (0.5..2.0, default is #{options[:speed]})"
          ) do |speed|
    options[:speed] = speed.tap do |sp|
      abort "ERROR: #{sp} is not within (0.5..2.0)" unless (0.5..2.0).cover?(sp)
    end
  end

  opts.on('-D DIR', '--output-directory DIR',
          'Directory to put converted files in, default is "."') do |dir|
    options[:dir] = Pathname.new(File.expand_path(dir)).tap do |d|
      abort "ERROR: '#{d}' is not a valid directory" unless d.directory?
    end
  end

  opts.on('--[no-]keep-original', 'Keep original files.') do |keep|
    options[:keep_original] = keep
  end

  opts.on('--[no-]fat32',
          'Replace characters forbidden in Fat32 in filenames.') do |fat32|
    options[:fat32] = fat32
  end

  opts.on '-h', '--help', 'Display this message' do
    puts opts
    exit
  end
end

if __FILE__ == $PROGRAM_NAME
  ARGV << '--help' if ARGV.empty?
  parser.parse!

  if ARGV.empty?
    warn 'No files to process, exiting'
    exit 1
  end

  ARGV.each do |file|
    old = Pathname.new(file)
    ext = old.extname

    new_basename = "#{old.basename(ext)}-#{options[:speed]}x.mp3"
    new_basename = new_basename.gsub(/[:;\*\?"<>|]/, '_') if options[:fat32]

    new_location = options[:dir] + new_basename

    cmd = []

    cmd << 'ffmpeg'
    cmd << '-i' << old.to_s
    cmd << '-vn'                            # no video
    cmd << '-acodec' << 'mp3'
    cmd << '-filter:a' << "atempo=#{options[:speed]}"
    cmd << new_location.to_s

    system(*cmd)

    old.delete unless options[:keep_original]
  end
end
