#! /usr/bin/env ruby

=begin

Generate flexget (http://flexget.com) configuration file based on
simple-structured input config.

Created: 16 Nov 2013
Author: Victor Deryagin <vderyagin@gmail.com>

=end

require 'yaml'

def config_file
  File.expand_path('~/.flexget/config.yml')
end

def input_file
  File.expand_path('~/.flexget/input.yml')
end

def default_download_dir
  File.expand_path('~')
end

def input
  YAML.load_file(input_file)
end

def output
  {
    'tasks' => tasks,
    'templates' => templates
  }
end

def tasks
  input.each_with_object({}) do |(category, list), task|
    list.each do |name, url|
      task[name] = {
        'template' => category.sub(/(s|_channels|_playlists)\z/, ''),
        'rss' => url_for(category, url)
      }
    end
  end
end

def url_for(category, string)
  case
  when string[/\Ahttp/]
    string
  when category == 'youtube_channels'
    "http://gdata.youtube.com/feeds/base/users/#{string}/uploads"
  when category == 'youtube_playlists'
    "http://gdata.youtube.com/feeds/api/playlists/#{string}"
  else
    fail "dunno what to do with this thing: '#{string}'"
  end
end

def templates
  {
    'video-feed' => {
      'download' => ENV['VIDEO_DOWNLOAD_DIR'] || default_download_dir
    },
    'podcast' => {
      'download' => ENV['PODCASTS_DIR'] || default_download_dir
    },
    'youtube' => {
      'exec' => {
        'on_output' => {
          'for_accepted' => 'yt {{url}}'
        }
      }
    },
    'global' => {
      'headers' => {
        'User-Agent' => 'Mozilla/5.0 (X11; Linux x86_64; rv:25.0) Gecko/20100101 Firefox/25.0'
      },
      'accept_all' => true
    }
  }
end

File.write config_file, YAML.dump(output) if __FILE__ == $PROGRAM_NAME
