#! /usr/bin/env ruby

=begin

Output list of files in git repository sorted by number of times changed.

Created: 7 Nov 2012
Author: Victor Deryagin <vderyagin@gmail.com>

=end

GIT_DIR = ENV['GIT_WORK_TREE']
CMD = ['git', 'log', '--name-only', '--pretty=format:""']

changes = IO.popen(CMD).each_line.with_object(Hash.new(0)) { |line, files|
  next if line == "\n"
  line.chomp!
  files[line] += 1 if File.file?(File.expand_path(line, GIT_DIR))
}.to_a.sort_by(&:last)

num_field_size = changes.last.last.to_s.size

changes.reverse_each do |file, churn|
  printf "%-#{num_field_size}d %s\n", churn, file
end
