#! /usr/bin/env ruby

=begin

Serve static files in directory via http.

Created: 23 Jun 2012
Author: Victor Deryagin <vderyagin@gmail.com>

=end

require 'webrick'
require 'optparse'

options = {
  Port:         9090,
  DocumentRoot: Dir.pwd
}

OptionParser.new do |opts|
  executable_name = File.basename($PROGRAM_NAME)

  opts.banner = "Usage: #{executable_name} [OPTIONS] [DIR]"

  opts.separator ''
  opts.separator 'Options:'

  opts.on '-h', '--help', 'Display this message' do
    puts opts
    exit
  end

  opts.on '-p', '--port PORT', Integer, 'Port to serve on' do |port|
    options[:Port] = port
  end
end.parse! ARGV

options[:DocumentRoot] = ARGV.first unless ARGV.empty?

server = WEBrick::HTTPServer.new(options)

trap :INT do
  server.shutdown
end

puts "Serving #{options[:DocumentRoot]} on 0.0.0.0:#{options[:Port]}"
server.start
