#! /usr/bin/env ruby

=begin

Update specified version control repositories.
Shells out to git(1), hg(1), cvs(1), darcs(1), svn(1), bzr(1) as needed.

Created: 23 Apr 2013
Author: Victor Deryagin <vderyagin@gmail.com>

=end

def has_dir(dir)
  ->(d, pdir) {
    File.directory?(File.expand_path(d, pdir))
  }.curry[dir]
end

if __FILE__ == $PROGRAM_NAME
  if ARGV.empty?
    puts "Usage: #{File.basename(__FILE__)} DIRECTORY..."
    exit
  end

  ARGV.each do |directory|
    Dir.chdir directory do
      command =
        case Dir.pwd
        when has_dir('.bzr')   then ['bzr', 'pull']
        when has_dir('CVS')    then ['cvs', 'update']
        when has_dir('_darcs') then ['darcs', 'pull']
        when has_dir('.git')   then ['git', 'pull']
        when has_dir('.hg')    then ['hg', 'pull', '-u']
        when has_dir('.svn')   then ['svn', 'update']
        else
          warn "#{directory} is not a valid repository."
          exit 1
        end

      printf "in %s:\n", Dir.pwd
      system(*command)
    end
  end
end
