#! /usr/bin/env ruby

=begin

Update specified version control repositories.
Shells out to git(1), hg(1), cvs(1), darcs(1), svn(1), bzr(1) as needed.

Created: 23 Apr 2013
Author: Victor Deryagin <vderyagin@gmail.com>

=end

def dir?(dir)
  lambda { |directory, parent|
    File.directory?(File.expand_path(directory, parent))
  }.curry[dir]
end

if __FILE__ == $PROGRAM_NAME
  puts "Usage: #{File.basename(__FILE__)} DIRECTORY..." if ARGV.empty?

  ARGV.select(&(File.method(:directory?))).each do |directory|
    Dir.chdir directory do
      command =
        case Dir.pwd
        when dir?('.bzr')   then %w(bzr pull)
        when dir?('CVS')    then %w(cvs update)
        when dir?('_darcs') then %w(darcs pull)
        when dir?('.git')   then %w(git pull --rebase=false)
        when dir?('.hg')    then %w(hg pull --update)
        when dir?('.svn')   then %w(svn update)
        else next
        end

      puts "in #{Dir.pwd}:"
      system(*command)
    end
  end
end
