#! /usr/bin/env ruby

EXTRACT_LAYOUT_REGEX = /\sconnected\s[\dx+]+\s(?:(?<layout>[^\s]+)\s+)?\(/

next_layout = case `xrandr --query`[EXTRACT_LAYOUT_REGEX, :layout]
              when 'left' then 'normal'
              when nil    then 'left'
              else fail 'unknown screen orientation'
              end

system 'xrandr', '--orientation', next_layout
system 'killall', '-9', 'dzen2'
system 'xmonad', '--restart'
